services:
  mail:
    image: bytemark/smtp
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - SETUID
      - SETGID

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - SETUID
      - SETGID
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - SETUID
      - SETGID
    volumes:
      - ./data/event:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - SETUID
      - SETGID
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    expose:
      - "8000"
#    environment:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.entrypoints=websecure"
      - "traefik.http.routers.plausible.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.plausible.tls.certresolver=http-challenge"
    env_file:
      - plausible-conf.env
    networks:
      - default
      - traefik-proxy

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
networks:
  default:
  traefik-proxy:
    external: true
